02 model spec
KentarouTawara/sample_app_for_rspec pull request #2
Opened 2020-07-04 07:24 UTC by KentarouTawara

## 概要
taskモデルのモデルスペックを作成しました。

## 確認方法
下記のような出力を得ました。
[![Image from Gyazo](https://i.gyazo.com/724283c7512811d4677b0b1a14ce0fc9.png)](https://gyazo.com/724283c7512811d4677b0b1a14ce0fc9)

2020-07-04 08:01 UTC, KentarouTawara commented
## 解答を確認したので、下記を修正する
・変数の役割や内容が分かる様な名前をつける
・FactoryBot.createを代入したローカル変数からtitleを取得して、重複データを作る
・taskのFactoryにassociationを定義してuserの記述を省略する
・FactoryBot.の部分を省略する設定をする
・unique制約のあるカラムはsequenceを利用する

2020-07-05 05:42 UTC, KentarouTawara commented
・変数の役割や内容が分かる様な名前をつける
→ 4c2f48f 
・FactoryBot.createを代入したローカル変数からtitleを取得して、重複データを作る
→ 38e9257 
・taskのFactoryにassociationを定義してuserの記述を省略する
→ 71e3cb4
・FactoryBot.の部分を省略する設定をする
→ 1a82c9f
・unique制約のあるカラムはsequenceを利用する
→ 0943934

・`.valid?`よりも`be_invalid` のほうがよいでしょうか？ (Qiitaで見かけた記事を参考にしただけです)
・includeよりeqのほうがよいでしょうか？
・title: nil より title:"" のほうがよいでしょうか？

2020-07-05 05:47 UTC, yuji91 requested changes

2020-07-05 05:47 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status { 'todo' }
enumの設定値だと分かるので、シンボルにしておいた方がベターです！
```suggestion
    status { :todo }
```

2020-07-05 05:55 UTC, yuji91 requested changes
> .valid?よりもbe_invalid のほうがよいでしょうか？

`.valid?`はマッチャではないので、`be_valid`で記載した方が簡潔かなと思います。
`.valid?`の結果が`true`であることをexpectするのか、
`be_valid`であることをexpectするのかという書き方の違いなので、細かい部分にはなります！

> includeよりeqのほうがよいでしょうか？

これはケースバイケースだと思います。
完全に一致することを強調したいケースでは`eq`を使うべきですし、文言が変わりやすい部分だったり、必要な内容が含まれていれば十分であれば`include`で良いかなと思います。

迷ったら「変更が発生してまた直すことになりそうだからincludeにしておく」のか、
「まず変更することはないから範囲の狭いeqにしておく」くらいの感覚で良いかと思います。

> title: nil より title:"" のほうがよいでしょうか？

これは対象がnilをまず受け付けられるのかという前提がありますが、空文字を入力していることを強調したいなら`""`と記載した方が良いかもしれません。
`nil`と書いた方が見映えが良くテストコードの見通しが良い場合はそちらでも良いと思います。

これらの点は挙動に問題がなければあとはフォーマットの問題なので、自分なりにどういう意図で書いているかだけ意識して、後は既存のテストコードがあればそちらに合わせた方が全体として統一された書き方で見やすいので合わせた方が良いかと！

2020-07-05 07:16 UTC, KentarouTawara commented on spec/factories/tasks.rb
> +    status { 'todo' }
655cf97 にて修正しました。

2020-07-05 07:22 UTC, KentarouTawara commented
>  .valid?よりもbe_invalid のほうがよいでしょうか？

cf510b9 

>includeよりeqのほうがよいでしょうか？

24a9072

>title: nil より title:"" のほうがよいでしょうか？

168a0b0

解答の下記の部分は、タイトルのユニーク制約を裏付けるテストだと思うのですが、これも付け足したほうがよいでしょうか？すべてOKの場合のテストが先頭にある場合でも、このテストは必要なのでしょうか？  

    it 'is valid with another title' do
      task_with_another_title = build(:task, title: 'another_title')
      expect(task_with_another_title).to be_valid
      expect(task_with_another_title.errors).to be_empty
    end

2020-07-05 07:36 UTC, yuji91 approved these changes
> 解答の下記の部分は、タイトルのユニーク制約を裏付けるテストだと思うのですが、これも付け足したほうがよいでしょうか？

この解答例はかなり丁寧にテストを書いているので、エラーとして確認したいケースが記載されていれば十分だと思ってもらって大丈夫です！

> すべてOKの場合のテストが先頭にある場合でも、このテストは必要なのでしょうか？

これはユニーク制約をテストするという観点で、下記の2ケースを作成した形となります。
- ユニーク制約に違反した場合に、テストNGとなること
- ユニーク制約に違反していない場合に、テストOKとなること

最初のケースは下記の疎通テストとなるので、観点が違うものという点は抑えて欲しいです。
- 入力項目が正常の場合に、テストOKとなること
（ユニーク制約のテストであれば「既にデータが登録されていること」と言う前提があるかと思います。）

必要か不要かで言うと、なくても大丈夫です！
テストケースのカバー的な意味合いで追加している形になりますね。

このPullRequestで残りの修正点は特にないので、マージして次に進んで大丈夫です！

2020-07-05 07:42 UTC, merged